"""enhance_orders_table

Revision ID: 254fec74154b
Revises: e3a420d60386
Create Date: 2025-07-05 22:11:50.369353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254fec74154b'
down_revision: Union[str, None] = 'e3a420d60386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'delivery_method')
    op.drop_column('orders', 'delivery_phone')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
