"""add order field to product_specifications

Revision ID: e3a420d60386
Revises: 9a5beeada4c2
Create Date: 2025-07-01 21:24:57.854724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a420d60386'
down_revision: Union[str, None] = '9a5beeada4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Добавляем поле с nullable=True и default=0
    op.add_column('product_specifications', sa.Column('order', sa.Integer(), nullable=True, server_default='0'))
    # 2. Обновляем все существующие строки (если нужно, можно выставить по id)
    op.execute('UPDATE product_specifications SET "order" = 0 WHERE "order" IS NULL')
    # 3. Делаем поле NOT NULL
    op.alter_column('product_specifications', 'order', nullable=False, server_default=None)
    # 4. Остальные изменения
    op.alter_column('products', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
        sa.Column('token', sa.String(255), unique=True, nullable=False),
        sa.Column('expires_at', sa.DateTime, nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('product_specifications', 'order')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
